development:
  adapter: postgresql
  encoding: unicode
  database: todojavascript_development
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: todojavascript_production
  pool: 5
